---
application:
  name: "qba-license-manager"
  project: "qba-license-manager"
  organization: "QoveryCommunity"
  storage:
  - name: "storage"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/storage"
routers:
- name: "main-qba-license-manager"
  routes:
  - application_name: "qba-license-manager"
    paths:
    - "/*"
